### ISSUE TITLE
Removing old VMT cause error with migration feature

### ISSUE THREAD

**Issue by paoolo** [dice-cyfronet/atmosphere#88]
```
Failed Atmosphere::Cloud::RemoveOlderVmtWorker with [1215]: PG::ForeignKeyViolation: ERROR:  update or delete on table "atmosphere_virtual_machine_templates" violates foreign key constraint "atmo_mj_vmt_fk" on table "atmosphere_migration_jobs"
DETAIL:  Key (id)=(1212) is still referenced from table "atmosphere_migration_jobs".
: DELETE FROM "atmosphere_virtual_machine_templates" WHERE "atmosphere_virtual_machine_templates"."id" = $1. Manual intervention required!
```

**Comment by paoolo** [comment]
Due to #15.

**Comment by paoolo** [comment]
@mkasztelnik do I need to add a cascade delete or something other?

**Comment by mkasztelnik** [comment]
```
/home/atmosphere/current/vendor/bundle/ruby/2.1.0/bundler/gems/atmosphere-7ddeeffe4ae6/app/models/atmosphere/virtual_machine_template.rb:136:in `destroy'
/home/atmosphere/current/vendor/bundle/ruby/2.1.0/bundler/gems/atmosphere-7ddeeffe4ae6/app/workers/atmosphere/vm_template_monitoring_worker.rb:36:in `block in update_images'
/home/atmosphere/current/vendor/bundle/ruby/2.1.0/bundler/gems/atmosphere-7ddeeffe4ae6/app/workers/atmosphere/vm_template_monitoring_worker.rb:35:in `each'
/home/atmosphere/current/vendor/bundle/ruby/2.1.0/bundler/gems/atmosphere-7ddeeffe4ae6/app/workers/atmosphere/vm_template_monitoring_worker.rb:35:in `update_images'
/home/atmosphere/current/vendor/bundle/ruby/2.1.0/bundler/gems/atmosphere-7ddeeffe4ae6/app/workers/atmosphere/vm_template_monitoring_worker.rb:14:in `perform'
```

**Comment by paoolo** [comment]
Error is reproduce-able.

**Comment by paoolo** [comment]
Testing on dev if fix works.

**Comment by paoolo** [comment]
Fixed in https://github.com/dice-cyfronet/atmosphere/commit/bf4364563dfa5a7880cd2016e084168e26447fee, https://github.com/dice-cyfronet/atmosphere/commit/1cd33348d26e5abbf46a8541c2e3ce93e7cf98ac and https://github.com/dice-cyfronet/atmosphere/commit/b0aba54f804b4caaa144fac0796f092f1905d060
