### ISSUE TITLE
Error during removing appliance set

### ISSUE THREAD

**Issue by paoolo** [dice-cyfronet/atmosphere#92]
Port mapping was removed.

```
Billing appliance 29911 for 0.11769597535722222 hours of use.
Calculated hourly charge for using VM 36668 is 0. This VM currently has 1 appliances using it.
Applying charge of 0 to appliance 29911 and deducting it from balance of fund 1.
I, [2015-01-20T13:12:02.134810 #19514]  INFO -- : delete http://IP:8400/dnat/VM_IP/22/tcp
D, [2015-01-20T13:12:02.134961 #19514] DEBUG -- request: Authorization: "Basic XXX"
User-Agent: "Faraday v0.9.1"
I, [2015-01-20T13:12:02.142011 #19514]  INFO -- Status: 404
D, [2015-01-20T13:12:02.142108 #19514] DEBUG -- response: content-type: "application/json"
content-length: "0"
x-content-type-options: "nosniff"
connection: "close"
server: "thin 1.6.2 codename Doc Brown"
Wrangler returned 404 when trying to remove redirections for IP VM_IP, port 22, protocol tcp.
ActiveRecord::RecordNotDestroyed: ActiveRecord::RecordNotDestroyed
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/persistence.rb:167:in `destroy!'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/has_many_association.rb:112:in `each'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/has_many_association.rb:112:in `delete_records'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:492:in `remove_records'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:485:in `block in delete_or_destroy'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:167:in `transaction'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:485:in `delete_or_destroy'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:270:in `destroy'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:208:in `destroy_all'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/has_many_association.rb:26:in `handle_dependency'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/builder/association.rb:135:in `block in add_before_destroy_callbacks'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:440:in `instance_exec'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:440:in `block in make_lambda'
... 90 levels...
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:263:in `destroy'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/persistence.rb:167:in `destroy!'
	from (irb):4
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/commands/console.rb:90:in `start'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/commands/console.rb:9:in `start'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/atmosphere/current/vendor/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

**Comment by mkasztelnik** [comment]
This is already fixed by https://github.com/dice-cyfronet/atmosphere/pull/96 and https://github.com/dice-cyfronet/ip-wrangler/pull/7
